# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'INTENCITY-METER' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for INTENCITY-METER
	pod 'ABGaugeViewKit'

end
